export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
export const LOADING_PRODUCTS_SUCCESS = "LOADING_PRODUCTS_SUCCESS";
export const LOADING_PRODUCTS_ERROR = "LOADING_PRODUCTS_ERROR";
